[project]
name = "capstone-starter"
version = "0.1.0"
description = "Capstone Starter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.0.3",
    "sqlalchemy==2.0.30",
    "psycopg2-binary==2.9.9",
    "alembic==1.13.1",
    "gunicorn>=23.0.0",
]
